#!/usr/bin/env python3
import asyncio
import argparse
import sys

from aiogoogletrans import Translator


async def main():
    parser = argparse.ArgumentParser(
        description='Python Google Translator as a command-line tool')
    parser.add_argument('text', help='The text you want to translate.')
    parser.add_argument('-d', '--dest', default=None,
        help='The destination language you want to translate. (Default: en)')
    parser.add_argument('-s', '--src', default=None,
        help='The source language you want to translate. (Default: auto)')

    args = parser.parse_args()

    translator = Translator()
    try:
        result = await translator.translate(args.text, dest=args.dest, src=args.src)
    except ValueError:
        result = 'Invalid language given'
    else:
        result = f"""
[{result.src}] {result.origin}
    ->
[{result.dest}] {result.text}
[pron.] {result.pronunciation}
        """.strip()

    print(result)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
